-- Your SQL goes here
CREATE TABLE games (
	id SERIAL PRIMARY KEY,
	next_battle TIMESTAMP,
	current_round INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	published BOOLEAN NOT NULL DEFAULT 'f'
);
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(32) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	salt VARCHAR NOT NULL,
	currency INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE lobbys (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	passphrase VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE lobby_users (
	id SERIAL UNIQUE,
	lobby_id INT NOT NULL,
	user_id INT NOT NULL UNIQUE,
	username VARCHAR(32) UNIQUE NOT NULL,
	ready BOOLEAN NOT NULL DEFAULT 'f',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(lobby_id, user_id),
	CONSTRAINT fk_lobby FOREIGN KEY(lobby_id) REFERENCES lobbys(id) ON DELETE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT fk_username FOREIGN KEY(username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE game_users (
	id SERIAL UNIQUE,
	game_id INT NOT NULL,
	user_id INT NOT NULL UNIQUE,
	username VARCHAR(32) UNIQUE NOT NULL,
	health INT NOT NULL,
	credits INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(game_id, user_id),
	CONSTRAINT fk_game FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT fk_username FOREIGN KEY(username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE
);
create TABLE game_user_characters (
	game_user_id INT PRIMARY KEY,
	character_id INT NOT NULL,
	position INT NOT NULL,
	upgraded BOOLEAN NOT NULL DEFAULT 'f',
	attack_bonus INT NOT NULL DEFAULT 0,
	defense_bonus INT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(game_user_id, position),
	CONSTRAINT fk_game_user FOREIGN KEY(game_user_id) REFERENCES game_users(id) ON DELETE CASCADE,
	CHECK (
		position >= 0
		AND position < 12
	) -- 7 for board + 5 for hand
);